easy_admin:
    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    entities:
        Post:
            class: App\Entity\Post
        User:
            class: App\Entity\User
