easy_admin:
    site_name: '<img src="/build/img/logoblanc.png">'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'

    design:
        assets:
            css:
                - '/build/admin.css'
            js:
                - '/build/admin.js'


        menu:
            - { entity: 'Post', icon: 'file' }
            - { entity: 'Category', icon: 'archive' }

    entities:
        Post:
            class: App\Entity\Post
            label: 'Post'

            list:
                title: 'Post'
                fields:
                    - { property: 'published', label: 'Visible'}
                    - { property: 'image', type: 'image', base_path: '%app.path.post_images%'}
                    - { property: 'title', label: 'Titre' }
                    - { property: 'Author', label: 'Auteur'}
                    - { property: 'createdAt', label: 'Date de création'}


            form:
                fields:
                    - { type: 'group', columns: 8, label: 'Basic information', icon: 'edit' }
                    - { property: 'title', label: 'titre'}
                    - { property: 'metaDescription', label: 'Description'}
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor'}

                    - { type: 'group', columns: 4, label: 'Illustration', icon: 'image' }
                    - { property: 'imageFile',label: 'Image', type: 'vich_image' }

                    - { type: 'group', columns: 8, label: 'Visibilité', icon: 'eye' }
                    - { property: 'published', label: 'Publier ce post'}




                    - { type: 'group', columns: 4, label: 'Classement', icon: 'archive' }
                    - { property: 'tags',type: 'App\Form\Type\TagsInputType', type_options: { help: 'Les tags doivent etres séparé par des virgules'}}
                    - { type: 'section' }
                    - { property: 'category', label: 'Catégorie', type: 'entity', type_options: {expanded: true}}

        Category:
            class: App\Entity\Category
            label: 'Catégorie'

            list:
                title: 'Catégorie'
                fields:
                    - { property: 'name', label: 'Nom'}

            edit:
                title: 'Modifier %%entity_label%%  (#%%entity_id%%)'
                fields:
                    - { property: 'name', label: 'Nom'}

            new:
                title: 'Nouvelle %%entity_label%%'
                fields:
                     - { property: 'name', label: 'Nom'}







