easy_admin:
    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    entities:
        Post:
            class: App\Entity\Post

            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.post_images%' }

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.post_images%' }

            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        User:
            class: App\Entity\User
